name: VeronicaSetterhall
favicon: null
layout_spectrum: 0.10177263896912336
typography_spectrum: 0.8894058624282479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#302217'
    - '#fcf3a8'
    - '#534a2d'
    - '#7e7844'
    - '#d4a067'
  brandStrength: 0.9874642686918378
  lightness: 0.0993565481621772
  saturation: 0.5517318537458777
  rhythmicContrast: 0.6704614795744419
purpose: []
